function D = acrobot_inertia_matrix(l1,l2,m1,m2,mt,ph1,ph2,th1,th2)
%ACROBOT_INERTIA_MATRIX
%    D = ACROBOT_INERTIA_MATRIX(L1,L2,M1,M2,MT,PH1,PH2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    19-Oct-2017 16:22:50

t2 = sin(th1);
t3 = ph1-ph2;
t4 = cos(th1);
t5 = l1.^2;
t6 = m2.*4.0;
t7 = mt.*4.0;
t8 = m1+t6+t7;
t9 = sin(t3);
t10 = cos(th2);
t11 = sin(th2);
t12 = cos(t3);
t13 = l1.*l2.*m2.*t4.*t10.*t12.*(1.0./2.0);
t14 = l1.*l2.*m2.*t4.*t9.*t11.*(1.0./2.0);
t15 = t4.*t10;
t16 = cos(ph1);
t17 = cos(ph2);
t18 = t2.*t11.*t16.*t17;
t19 = sin(ph1);
t20 = sin(ph2);
t21 = t2.*t11.*t19.*t20;
t22 = t15+t18+t21;
t23 = l1.*l2.*m2.*t22.*(1.0./2.0);
t24 = l2.^2;
D = reshape([t5.*t8.*(t2.^2-1.0).*(-1.0./4.0),0.0,t13,t14,0.0,t5.*t8.*(1.0./4.0),l1.*l2.*m2.*t2.*t9.*t10.*(-1.0./2.0),t23,t13,l1.*l2.*m2.*t2.*t9.*t10.*(-1.0./2.0),m2.*t24.*(t11.^2-1.0).*(-1.0./4.0),0.0,t14,t23,0.0,m2.*t24.*(1.0./4.0)],[4,4]);
