function KE = acrobot_kinetic_energy(dph1,dph2,dth1,dth2,l1,l2,m1,m2,ph1,ph2,th1,th2)
%ACROBOT_KINETIC_ENERGY
%    KE = ACROBOT_KINETIC_ENERGY(DPH1,DPH2,DTH1,DTH2,L1,L2,M1,M2,PH1,PH2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    24-Oct-2017 05:15:47

t3 = cos(ph1);
t4 = cos(th1);
t5 = cos(ph2);
t6 = cos(th2);
t7 = sin(ph1);
t8 = sin(th1);
t9 = sin(ph2);
t10 = sin(th2);
t2 = dph1.*l1.*t4.*t7+dph2.*l2.*t6.*t9+dth1.*l1.*t3.*t8+dth2.*l2.*t5.*t10;
t11 = dph1.*l1.*t3.*t4+dph2.*l2.*t5.*t6-dth1.*l1.*t7.*t8-dth2.*l2.*t9.*t10;
t12 = dth1.*l1.*t4+dth2.*l2.*t6;
t13 = dph1.^2;
KE = m2.*(t2.^2+t11.^2+t12.^2).*(1.0./2.0)+l1.^2.*m1.*(t13-t8.^2.*t13+dth1.^2).*(1.0./2.0);
