function PE = acrobot_potential_energy(g,l1,l2,m1,m2,ph1,ph2,th1,th2)
%ACROBOT_POTENTIAL_ENERGY
%    PE = ACROBOT_POTENTIAL_ENERGY(G,L1,L2,M1,M2,PH1,PH2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    24-Oct-2017 05:15:48

t2 = cos(ph1);
t3 = cos(th1);
PE = g.*m2.*(l2.*cos(ph2).*cos(th2)+l1.*t2.*t3)+g.*l1.*m1.*t2.*t3;
