function D = acrobot_inertia_matrix(l1,l2,m1,m2,ph1,ph2,th1,th2)
%ACROBOT_INERTIA_MATRIX
%    D = ACROBOT_INERTIA_MATRIX(L1,L2,M1,M2,PH1,PH2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    24-Oct-2017 05:15:48

t2 = sin(th1);
t3 = ph1-ph2;
t4 = cos(th1);
t5 = l1.^2;
t6 = m1+m2;
t7 = sin(t3);
t8 = cos(th2);
t9 = sin(th2);
t10 = cos(t3);
t11 = l1.*l2.*m2.*t4.*t8.*t10;
t12 = l1.*l2.*m2.*t4.*t7.*t9;
t13 = t4.*t8;
t14 = cos(ph1);
t15 = cos(ph2);
t16 = t2.*t9.*t14.*t15;
t17 = sin(ph1);
t18 = sin(ph2);
t19 = t2.*t9.*t17.*t18;
t20 = t13+t16+t19;
t21 = l1.*l2.*m2.*t20;
t22 = l2.^2;
D = reshape([-t5.*t6.*(t2.^2-1.0),0.0,t11,t12,0.0,t5.*t6,-l1.*l2.*m2.*t2.*t7.*t8,t21,t11,-l1.*l2.*m2.*t2.*t7.*t8,-m2.*t22.*(t9.^2-1.0),0.0,t12,t21,0.0,m2.*t22],[4,4]);
