function H = acrobot_coriolis_and_gravity(dph1,dph2,dth1,dth2,g,l1,l2,m1,m2,mt,ph1,ph2,th1,th2)
%ACROBOT_CORIOLIS_AND_GRAVITY
%    H = ACROBOT_CORIOLIS_AND_GRAVITY(DPH1,DPH2,DTH1,DTH2,G,L1,L2,M1,M2,MT,PH1,PH2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    19-Oct-2017 16:22:50

t2 = sin(ph1);
t3 = sin(th1);
t4 = dph2.^2;
t5 = cos(th2);
t6 = cos(ph1);
t7 = sin(ph2);
t8 = dth2.^2;
t9 = cos(ph2);
t10 = sin(th2);
t11 = dph1.^2;
t12 = th1.*2.0;
t13 = sin(t12);
t14 = cos(th1);
t15 = dth1.^2;
H = [l1.*t14.*(g.*m1.*t2+g.*m2.*t2.*2.0+g.*mt.*t2.*2.0+dph1.*dth1.*l1.*m1.*t3+dph1.*dth1.*l1.*m2.*t3.*4.0+dph1.*dth1.*l1.*mt.*t3.*4.0-l2.*m2.*t2.*t4.*t5.*t9+l2.*m2.*t4.*t5.*t6.*t7-l2.*m2.*t2.*t5.*t8.*t9+l2.*m2.*t5.*t6.*t7.*t8+dph2.*dth2.*l2.*m2.*t2.*t7.*t10.*2.0+dph2.*dth2.*l2.*m2.*t6.*t9.*t10.*2.0).*(1.0./2.0);l1.*(g.*m1.*t3.*t6.*-2.0-g.*m2.*t3.*t6.*4.0-g.*mt.*t3.*t6.*4.0+l1.*m1.*t11.*t13.*(1.0./2.0)+l1.*m2.*t11.*t13.*2.0+l1.*mt.*t11.*t13.*2.0-l2.*m2.*t8.*t10.*t14.*2.0+l2.*m2.*t2.*t3.*t4.*t5.*t7.*2.0+l2.*m2.*t2.*t3.*t5.*t7.*t8.*2.0+l2.*m2.*t3.*t4.*t5.*t6.*t9.*2.0+l2.*m2.*t3.*t5.*t6.*t8.*t9.*2.0+dph2.*dth2.*l2.*m2.*t2.*t3.*t9.*t10.*4.0-dph2.*dth2.*l2.*m2.*t3.*t6.*t7.*t10.*4.0).*(-1.0./4.0);l2.*m2.*t5.*(g.*t7+dph2.*dth2.*l2.*t10+l1.*t2.*t9.*t11.*t14-l1.*t6.*t7.*t11.*t14+l1.*t2.*t9.*t14.*t15-l1.*t6.*t7.*t14.*t15+dph1.*dth1.*l1.*t2.*t3.*t7.*2.0+dph1.*dth1.*l1.*t3.*t6.*t9.*2.0).*(1.0./2.0);l2.*m2.*(g.*t9.*t10.*-2.0+l2.*t4.*t5.*t10-l1.*t3.*t5.*t15.*2.0+l1.*t2.*t7.*t10.*t11.*t14.*2.0+l1.*t2.*t7.*t10.*t14.*t15.*2.0+l1.*t6.*t9.*t10.*t11.*t14.*2.0+l1.*t6.*t9.*t10.*t14.*t15.*2.0-dph1.*dth1.*l1.*t2.*t3.*t9.*t10.*4.0+dph1.*dth1.*l1.*t3.*t6.*t7.*t10.*4.0).*(-1.0./4.0)];
