function H = acrobot_coriolis_and_gravity(dph1,dph2,dth1,dth2,g,l1,l2,m1,m2,ph1,ph2,th1,th2)
%ACROBOT_CORIOLIS_AND_GRAVITY
%    H = ACROBOT_CORIOLIS_AND_GRAVITY(DPH1,DPH2,DTH1,DTH2,G,L1,L2,M1,M2,PH1,PH2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    24-Oct-2017 05:15:48

t2 = sin(ph1);
t3 = sin(th1);
t4 = dph2.^2;
t5 = cos(th2);
t6 = cos(ph1);
t7 = sin(ph2);
t8 = dth2.^2;
t9 = cos(ph2);
t10 = sin(th2);
t11 = cos(th1);
t12 = dph1.^2;
t13 = l1.^2;
t14 = dth1.^2;
H = [l1.*t11.*(g.*m1.*t2+g.*m2.*t2+dph1.*dth1.*l1.*m1.*t3.*2.0+dph1.*dth1.*l1.*m2.*t3.*2.0-l2.*m2.*t2.*t4.*t5.*t9+l2.*m2.*t4.*t5.*t6.*t7-l2.*m2.*t2.*t5.*t8.*t9+l2.*m2.*t5.*t6.*t7.*t8+dph2.*dth2.*l2.*m2.*t2.*t7.*t10.*2.0+dph2.*dth2.*l2.*m2.*t6.*t9.*t10.*2.0);g.*l1.*m1.*t3.*t6+g.*l1.*m2.*t3.*t6-m1.*t3.*t11.*t12.*t13-m2.*t3.*t11.*t12.*t13+l1.*l2.*m2.*t8.*t10.*t11-l1.*l2.*m2.*t2.*t3.*t4.*t5.*t7-l1.*l2.*m2.*t2.*t3.*t5.*t7.*t8-l1.*l2.*m2.*t3.*t4.*t5.*t6.*t9-l1.*l2.*m2.*t3.*t5.*t6.*t8.*t9-dph2.*dth2.*l1.*l2.*m2.*t2.*t3.*t9.*t10.*2.0+dph2.*dth2.*l1.*l2.*m2.*t3.*t6.*t7.*t10.*2.0;l2.*m2.*t5.*(g.*t7+dph2.*dth2.*l2.*t10.*2.0+l1.*t2.*t9.*t11.*t12+l1.*t2.*t9.*t11.*t14-l1.*t6.*t7.*t11.*t12-l1.*t6.*t7.*t11.*t14+dph1.*dth1.*l1.*t2.*t3.*t7.*2.0+dph1.*dth1.*l1.*t3.*t6.*t9.*2.0);-l2.*m2.*(-g.*t9.*t10+l2.*t4.*t5.*t10-l1.*t3.*t5.*t14+l1.*t2.*t7.*t10.*t11.*t12+l1.*t2.*t7.*t10.*t11.*t14+l1.*t6.*t9.*t10.*t11.*t12+l1.*t6.*t9.*t10.*t11.*t14-dph1.*dth1.*l1.*t2.*t3.*t9.*t10.*2.0+dph1.*dth1.*l1.*t3.*t6.*t7.*t10.*2.0)];
